apiVersion: v1
kind: PersistentVolume
metadata:
  name: prod-backup-pv
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.110
    path: "/volume1/homelab/dell"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prod-backup-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-prod-backup
  namespace: cron-jobs
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          nodeName: dell-slave
          nodeSelector:
            kubernetes.io/arch: amd64
          containers:
            - name: cron-prod-backup
              image: cr.yandex/crpoghn06qpit3061gka/cron-prod-backup:0.1.2-amd64
              imagePullPolicy: IfNotPresent
              env:
                - name: PING_URL
                  value: "http://192.168.0.30/microservices/pingwin/ping?service=cron&path=prod-backup"
              volumeMounts:
                - mountPath: /source
                  name: data
                  readOnly: true
                - mountPath: /destination
                  name: sharedice
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: yandex
          volumes:
            - name: data
              hostPath:
                path: /production
            - name: sharedice
              persistentVolumeClaim:
                claimName: prod-backup-pvc
